server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "prometheus"
      path-mapping:
        prometheus: "metrics"

spring:
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: ${OAUTH2_ADMIN_URL}/oauth2/introspect
          client-id: empty
          client-secret: empty

hydra:
  adminUri: ${OAUTH2_ADMIN_URL}
