{
 "title": "[AWS] EC2",
 "description": "Visualize AWS EC2",
 "tags": [ "AWS" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(aws_ec2_info,name)"
    }
   },
   {
    "name": "instance_name",
    "label": "Tag Name",
    "query": {
     "query": "label_values(aws_ec2_info{name=~\"arn:aws:ec2:$region:(.+):instance/(.+)\"}, tag_Name)"
    }
   },
   {
    "name": "instance_id",
    "label": "Instance ID",
    "query": {
     "query": "label_values(aws_ec2_info{name=~\"arn:aws:ec2:$region:(.+):instance/(.+)\", tag_Name=\"$instance_name\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPUUtilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "InstanceId": "$instanceid" },
     "expr": "sum by(dimension_InstanceId) (aws_ec2_cpuutilization_average{dimension_InstanceId=~\"$instance_id\", region=~\"$region\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dimension_InstanceId}}",
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DiskOps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "InstanceId": "$instanceid" },
     "expr": "sum by(dimension_InstanceId) (aws_ec2_disk_read_ops_sum{dimension_InstanceId=~\"$instance_id\", region=~\"$region\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dimension_InstanceId}} Read",
     "metricName": "DiskReadOps",
     "namespace": "AWS/EC2",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "InstanceId": "$instanceid" },
     "expr": "sum by(dimension_InstanceId) (aws_ec2_disk_write_ops_sum{dimension_InstanceId=~\"$instance_id\", region=~\"$region\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dimension_InstanceId}} Write",
     "metricName": "DiskWriteOps",
     "namespace": "AWS/EC2",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DiskBytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "InstanceId": "$instanceid" },
     "expr": "sum by(dimension_InstanceId) (aws_ec2_disk_read_bytes_sum{region=~\"$region\", dimension_InstanceId=~\"$instance_id\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dimension_InstanceId}} Read",
     "metricName": "DiskReadBytes",
     "namespace": "AWS/EC2",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "InstanceId": "$instanceid" },
     "expr": "sum by(dimension_InstanceId) (aws_ec2_disk_write_bytes_sum{region=~\"$region\", dimension_InstanceId=~\"$instance_id\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dimension_InstanceId}} Write",
     "metricName": "DiskWriteBytes",
     "namespace": "AWS/EC2",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "InstanceId": "$instanceid" },
     "expr": "sum by(dimension_InstanceId) (aws_ec2_network_in_sum{region=~\"$region\", dimension_InstanceId=~\"$instance_id\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dimension_InstanceId}} In. Sum",
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "InstanceId": "$instanceid" },
     "expr": "avg by(dimension_InstanceId) (aws_ec2_network_in_average{region=~\"$region\", dimension_InstanceId=~\"$instance_id\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dimension_InstanceId}} In. Avg",
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "expr": "sum by(dimension_InstanceId) (aws_ec2_network_out_sum{region=~\"$region\", dimension_InstanceId=~\"$instance_id\"})",
     "legendFormat": "{{dimension_InstanceId}} Out. Sum"
    },
    {
     "expr": "avg by(dimension_InstanceId) (aws_ec2_network_out_average{region=~\"$region\", dimension_InstanceId=~\"$instance_id\"})",
     "legendFormat": "{{dimension_InstanceId}} Out. Avg"
    }
   ]
  },
  {
   "title": "NetworkPackets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "InstanceId": "$instanceid" },
     "expr": "avg by(dimension_InstanceId) (aws_ec2_network_packets_in_sum{region=~\"$region\", dimension_InstanceId=~\"$instance_id\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dimension_InstanceId}} In",
     "metricName": "NetworkPacketsIn",
     "namespace": "AWS/EC2",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "InstanceId": "$instanceid" },
     "expr": "avg by(dimension_InstanceId) (aws_ec2_network_packets_out_sum{region=~\"$region\", dimension_InstanceId=~\"$instance_id\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dimension_InstanceId}} Out",
     "metricName": "NetworkPacketsOut",
     "namespace": "AWS/EC2",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "StatusCheck",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "InstanceId": "$instanceid" },
     "expr": "sum by(dimension_InstanceId) (aws_ec2_status_check_failed_sum{region=~\"$region\", dimension_InstanceId=~\"$instance_id\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dimension_InstanceId}} Failed",
     "metricName": "StatusCheckFailed",
     "namespace": "AWS/EC2",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "InstanceId": "$instanceid" },
     "expr": "sum by(dimension_InstanceId) (aws_ec2_status_check_failed_instance_sum{region=~\"$region\", dimension_InstanceId=~\"$instance_id\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dimension_InstanceId}} Failed. Instance",
     "metricName": "StatusCheckFailed_Instance",
     "namespace": "AWS/EC2",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "InstanceId": "$instanceid" },
     "expr": "sum by(dimension_InstanceId) (aws_ec2_status_check_failed_system_sum{region=~\"$region\", dimension_InstanceId=~\"$instance_id\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dimension_InstanceId}} Failed. System",
     "metricName": "StatusCheckFailed_System",
     "namespace": "AWS/EC2",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "options": {
    "content": "<a style=\"float: right\" href=\"http://www.monitoringartist.com\" target=\"_blank\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a>\n<div style=\"float: left\">\n<a target=\"_blank\" href=\"http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ec2-metricscollected.html\">AWS CloudWatch EC2 documentation</a>, \n<a target=\"_blank\" href=\"http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ebs-metricscollected.html\">AWS CloudWatch EBS documentation</a><br/>\n<a target=\"_blank\" href=\"https://grafana.net/dashboards/617\">Installed from Grafana.net dashboards</a>\n</div>\n<div style=\"clear:both; width:100%;height:0;font-size:0;\"></div>"
   },
   "targets": [
    {}
   ]
  }
 ]
}