{
 "title": "JVM (Micrometer)",
 "description": "Dashboard for Micrometer",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "service_name",
    "query": {
     "query": "label_values(jvm_memory_used,service_name)"
    }
   },
   {
    "name": "k8s_pod_name",
    "label": "k8s_pod_name",
    "query": {
     "query": "label_values(jvm_memory_used{service_name=\"$service_name\"},k8s_pod_name)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", area=\"nonheap\"},id)"
   },
   {
    "name": "jvm_buffer_pool",
    "label": "JVM Buffer Pools",
    "query": "label_values(jvm_buffer_memory_used{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"},id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", area=\"heap\"})*100/sum(jvm_memory_max{service_name=\"$service_name\",k8s_pod_name=\"$k8s_pod_name\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", area=\"nonheap\"})*100/sum(jvm_memory_max{service_name=\"$service_name\",k8s_pod_name=\"$k8s_pod_name\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "I/O Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ktor_http_server_requests_count{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}[$__rate_interval]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ktor_http_server_requests_count{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", status=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "HTTP - 5xx"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ktor_http_server_requests_sum{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", status!~\"5..\"}[$__rate_interval]))/sum(rate(ktor_http_server_requests_count{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", status!~\"5..\"}[$__rate_interval]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(ktor_http_server_requests_sum{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_threads_busy_threads{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "TOMCAT - BSY"
    },
    {
     "expr": "tomcat_threads_current_threads{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "TOMCAT - CUR"
    },
    {
     "expr": "tomcat_threads_config_max_threads{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "TOMCAT - MAX"
    },
    {
     "expr": "jetty_threads_busy{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "JETTY - BSY"
    },
    {
     "expr": "jetty_threads_current{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "JETTY - CUR"
    },
    {
     "expr": "jetty_threads_config_max{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "JETTY - MAX"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_memory_rss{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "rss"
    },
    {
     "expr": "process_memory_swap{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "process_memory_rss{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"} + process_memory_swap{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}[$__rate_interval])",
     "legendFormat": "process-15m"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "system-1m"
    },
    {
     "expr": "system_cpu_count{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "GC Pressure",
   "type": "graph",
   "description": "The percent of time spent on Garbage Collection over all CPUs assigned to the JVM process.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_count{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}[$__rate_interval])) by (service_name, k8s_pod_name) / on(service_name, k8s_pod_name) system_cpu_count",
     "legendFormat": "CPU time spent on GC"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "increase(logback_events_total{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}[$__rate_interval])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_files_open{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max_files{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "repeat": "persistence_counts",
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "repeat": "jvm_memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Collections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_count{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}[$__rate_interval])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_sum{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}[$__rate_interval])/rate(jvm_gc_pause_count{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}[$__rate_interval])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_max{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}[$__rate_interval])",
     "legendFormat": "allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}[$__rate_interval])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Classes loaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded{service_name=\"$service_name\",k8s_pod_name=\"$k8s_pod_name\"}[$__rate_interval])",
     "legendFormat": "delta-1m"
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_buffer_pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 75 },
   "repeat": "jvm_buffer_pool",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", id=~\"$jvm_buffer_pool\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", id=~\"$jvm_buffer_pool\"}",
     "legendFormat": "capacity"
    },
    {
     "expr": "jvm_buffer_count_buffers{service_name=\"$service_name\", k8s_pod_name=\"$k8s_pod_name\", id=~\"$jvm_buffer_pool\"}",
     "legendFormat": "buffers"
    }
   ]
  }
 ]
}