apiVersion: v1
kind: PersistentVolume
metadata:
  name: atlantis
  namespace: atlantis
  labels:
    type: local
    app: atlantis
spec:
  capacity:
    storage: 2Gi
  storageClassName: gp2
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/pv/atlantis"
