version: "3.3"

services:
  auth-server:
    image: docker.io/library/oauth2-server:0.0.1-SNAPSHOT
    ports:
      - "8082:8080"
      - "8002:8000"
    environment:
      BPL_DEBUG_ENABLED: "true"
  resource:
    image: docker.io/library/resource-server:0.0.1-SNAPSHOT
    ports:
      - "8081:8080"
      - "8001:8000"
    environment:
      BPL_DEBUG_ENABLED: "true"
#  client:
#    image: docker.io/library/client:0.0.1-SNAPSHOT
#    ports:
#      - "8080:80"