version: "3.8"

services:
  resource:
    build: "./resource-server"
    depends_on:
      - hydra
    ports:
      - "8080:8080"
    environment:
      OAUTH2_URL: "http://hydra:4445"
  hydra:
    build: "./hydra"
    depends_on:
      - db
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command: "serve all --dangerous-force-http"
    environment:
      - DSN=postgres://hydra:secret@db:5432/hydra
      - HYDRA_ADMIN_URL=http://hydra:4445/
  hydra-migrate:
    build: "./hydra"
    depends_on:
      - db
    command: "migrate sql -e --yes"
    environment:
      - DSN=postgres://hydra:secret@db:5432/hydra
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
