server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: http://127.0.0.1:4445/oauth2/introspect
          client-id: empty
          client-secret: empty
