# apiVersion: v1
# kind: Secret
# metadata:
#   name: hydra
#   namespace: account
#   labels:
#     app: hydra
# type: Opaque
# data:
#   SECRETS_SYSTEM: ""
#   DSN: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hydra
  namespace: account
  labels:
    app: hydra
data:
  HYDRA_ADMIN_URL: http://hydra:4445
  HYDRA_PUBLIC_URL: https://id.santelos.com/o
  URLS_LOGIN: https://id.santelos.com/login
  URLS_CONSENT: https://id.santelos.com/consent
  URLS_SELF_ISSUER: https://id.santelos.com/o
  LOG_LEVEL: debug
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra
  namespace: account
  labels:
    app: hydra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hydra
  template:
    metadata:
      labels:
        app: hydra
    spec:
      containers:
      - name: hydra
        image: docker.santelos.com/hydra
        command: ["hydra", "serve", "all", "--dangerous-force-http"]
        ports:
          - containerPort: 4445
          - containerPort: 4444
        envFrom:
          - configMapRef:
              name: hydra
          - secretRef:
              name: hydra
        resources:
          limits:
            memory: 50Mi
            cpu: 200m
          requests:
            memory: 50Mi
            cpu: 200m
        livenessProbe:
          httpGet:
            path: /health/alive
            port: 4445
          initialDelaySeconds: 3
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 4445
          initialDelaySeconds: 3
          failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: hydra
  namespace: account
spec:
  selector:
    app: hydra
  ports:
  - name: public
    protocol: TCP
    port: 4444
    targetPort: 4444
  - name: admin
    protocol: TCP
    port: 4445
    targetPort: 4445
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hydra
  namespace: account
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "id.santelos.com"
    secretName: id-santelos-cert
  rules:
  - host: id.santelos.com
    http:
      paths:
      - path: /o(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: hydra
            port:
              number: 4444
