apiVersion: v1
kind: PersistentVolume
metadata:
  name: hydra-db
  namespace: account
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/md0/hydra-db
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - pstroganov
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: hydra-db
#   namespace: account
#   labels:
#     app: hydra-db
# type: Opaque
# data:
#   POSTGRES_PASSWORD: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hydra-db
  namespace: account
  labels:
    app: hydra-db
data:
  POSTGRES_USER: hydra
  POSTGRES_DB: hydra
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hydra-db
  namespace: account
spec:
  replicas: 1
  serviceName: hydra-db
  selector:
    matchLabels:
      app: hydra-db
  template:
    metadata:
      labels:
        app: hydra-db
    spec:
      containers:
        - name: hydra-db
          image: postgres:14
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: hydra-db
            - secretRef:
                name: hydra-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: hydra-db-volume-claim
              subPath: postgres-data
  volumeClaimTemplates:
    - metadata:
        name: hydra-db-volume-claim
        labels:
          app: hydra-db
      spec:
        storageClassName: local-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: hydra-db
  namespace: account
  labels:
    app: hydra-db
spec:
  selector:
    app: hydra-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
