---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hydra
  labels:
    app: hydra
data:
  HYDRA_ADMIN_URL: http://hydra:4445
  HYDRA_PUBLIC_URL: https://id.santelos.com/o
  URLS_LOGIN: https://id.santelos.com/login
  URLS_CONSENT: https://id.santelos.com/consent
  URLS_SELF_ISSUER: https://id.santelos.com/o
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra
  labels:
    app: hydra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hydra
  template:
    metadata:
      labels:
        app: hydra
    spec:
      containers:
      - name: hydra
        image: 162173573602.dkr.ecr.ap-northeast-1.amazonaws.com/hydra
        command: ["hydra", "serve", "all", "--dangerous-force-http"]
        ports:
        - containerPort: 4445
        - containerPort: 4444
        envFrom:
          - configMapRef:
              name: hydra
          - secretRef:
              name: hydra
---
apiVersion: v1
kind: Service
metadata:
  name: hydra
spec:
  selector:
    app: hydra
  ports:
  - name: public
    protocol: TCP
    port: 4444
    targetPort: 4444
  - name: admin
    protocol: TCP
    port: 4445
    targetPort: 4445
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hydra
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: id.santelos.com
    http:
      paths:
      - path: /o(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: hydra
            port:
              number: 4444
