# apiVersion: v1
# kind: Secret
# metadata:
#   name: user-info-service
#   namespace: account
#   labels:
#     app: user-info-service
# type: Opaque
# data:
#   DATABASE__PASSWORD: ""
# ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-info-service
  namespace: account
  labels:
    app: user-info-service
data:
  OAUTH2__ADMIN_URI: "http://hydra:4445"
  DATABASE__HOST: "user-info-service-db"
  DATABASE__USERNAME: "user-info-service"
  DATABASE__DATABASE_NAME: "user-info-service"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-info-service
  namespace: account
  labels:
    app: user-info-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-info-service
  template:
    metadata:
      labels:
        app: user-info-service
    spec:
      containers:
      - name: user-info-service
        image: docker.santelos.com/user-info-service
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: user-info-service
          - secretRef:
              name: user-info-service
        resources:
          limits:
            memory: 150Mi
            cpu: 150m
          requests:
            memory: 150Mi
            cpu: 150m
---
apiVersion: v1
kind: Service
metadata:
  name: user-info-service
  namespace: account
spec:
  selector:
    app: user-info-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-info-service
  namespace: account
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "id.santelos.com"
    secretName: id-santelos-cert
  rules:
  - host: id.santelos.com
    http:
      paths:
      - path: /user-info(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: user-info-service
            port:
              number: 80
