apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
kubernetesVersion: v1.27.3
localAPIEndpoint:
  advertiseAddress: 192.168.0.186
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.27.3
networking:
  podSubnet: "10.244.0.0/16"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd