apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: fluentbit
  name: fluentbit
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: fluentbit
  template:
    metadata:
      labels:
        app: fluentbit
      name: fluentbit
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: fluentbit
      automountServiceAccountToken: true
      containers:
        - name: fluentbit
          image: cr.fluentbit.io/fluent/fluent-bit:2.2.2
          ports:
            - containerPort: 2020
          volumeMounts:
            - name: fluentbit-config
              mountPath: /fluent-bit/etc
            - mountPath: /var/log
              name: var-log
              readOnly: true
      volumes:
        - name: fluentbit-config
          configMap:
            name: fluentbit-config
        - hostPath:
            path: /var/log
          name: var-log
---
apiVersion: v1
kind: Service
metadata:
  name: fluentbit
  namespace: monitoring
spec:
  selector:
    app: fluentbit
  ports:
  - protocol: TCP
    port: 2020
    targetPort: 2020
