apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fluentbit.yaml
  - rbac.yaml
configMapGenerator:
  - name: fluentbit-config
    namespace: monitoring
    options:
      disableNameSuffixHash: true
    files:
      - fluent-bit.conf=fluentbit-config.conf
      - parsers.conf=fluentbit-parsers.conf
      - fluentbit-loki-filter.conf=fluentbit-loki-filter.conf
      - fluentbit-grafana-filter.conf=fluentbit-grafana-filter.conf
      - fluentbit-deluge-filter.conf=fluentbit-deluge-filter.conf
