apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fluentbit.yaml
  - rbac.yaml
configMapGenerator:
  - name: fluentbit-config
    namespace: monitoring
    options:
      disableNameSuffixHash: true
    files:
      - fluent-bit.conf=./config/fluentbit-config.conf
      - parsers.conf=./config/fluentbit-parsers.conf
      - fluentbit-inputs.conf=./config/fluentbit-inputs.conf
      - fluentbit-loki-filter.conf=./config/fluentbit-loki-filter.conf
      - fluentbit-grafana-filter.conf=./config/fluentbit-grafana-filter.conf
      - fluentbit-deluge-filter.conf=./config/fluentbit-deluge-filter.conf
      - fluentbit-fluentbit-filter.conf=./config/fluentbit-fluentbit-filter.conf
      - fluentbit-shardeum-filter.conf=./config/fluentbit-shardeum-filter.conf
