apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-db.yaml
  - grafana.yaml
configMapGenerator:
  - name: grafana-config
    namespace: monitoring
    options:
      disableNameSuffixHash: true
    files:
      - grafana.ini=grafana-config.ini
