server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: ${OAUTH2_URL}/oauth2/introspect
          client-id: empty
          client-secret: empty
