apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus.yaml
configMapGenerator:
  - name: prometheus-config
    namespace: monitoring
    options:
      disableNameSuffixHash: true
    files:
      - prometheus-config.yaml
