apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector
  namespace: monitoring
  labels:
    app: opentelemetry-collector
data:
  PROMETHEUS__HOST: "http://prometheus:9090"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: opentelemetry-collector
  namespace: monitoring
  labels:
    app: opentelemetry-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry-collector
  template:
    metadata:
      labels:
        app: opentelemetry-collector
    spec:
      containers:
      - name: opentelemetry-collector
        image: docker.santelos.com/opentelemetry-collector
        ports:
        - containerPort: 4317
        - containerPort: 55679
        - containerPort: 8888
        - containerPort: 13133
        envFrom:
          - configMapRef:
              name: opentelemetry-collector
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector
  namespace: monitoring
spec:
  selector:
    app: opentelemetry-collector
  ports:
  - protocol: TCP
    name: "grpc-receiver"
    port: 4317
    targetPort: 4317
  - protocol: TCP
    name: "zpages-extension"
    port: 55679
    targetPort: 55679
  - protocol: TCP
    name: "healthcheck-extension"
    port: 13133
    targetPort: 13133