apiVersion: v1
kind: Secret
metadata:
  name: opentelemetry-collector
  namespace: monitoring
  labels:
    app: opentelemetry-collector
type: Opaque
data:
  CLICKHOUSE__PASSWORD: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector
  namespace: monitoring
  labels:
    app: opentelemetry-collector
data:
  K8S_STATE_METRICS_HOST: "kube-state-metrics:8080"
  NODE_EXPORTER__HOST: "node-exporter:9100"
  PROMETHEUS__HOST: "http://prometheus:9090"
  CLICKHOUSE__HOST: "tcp://clickhouse:9000?dial_timeout=10s&compress=lz4"
  CLICKHOUSE__DATABASE: "otel"
  CLICKHOUSE__USERNAME: "opentelemetry_collector"
  INTERNET_CHECK_EXPORTER__HOST: "internet-checker.home.svc.cluster.local:9115"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: opentelemetry-collector
  namespace: monitoring
  labels:
    app: opentelemetry-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry-collector
  template:
    metadata:
      labels:
        app: opentelemetry-collector
    spec:
      serviceAccountName: opentelemetry-collector
      containers:
      - name: opentelemetry-collector
        image: docker.santelos.com/opentelemetry-collector
        imagePullPolicy: Always
        ports:
        - containerPort: 4317
        - containerPort: 55679
        env:
          - name: K8S_NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
        envFrom:
          - configMapRef:
              name: opentelemetry-collector
          - secretRef:
              name: opentelemetry-collector
        # resources:
        #   limits:
        #     memory: 150Mi
        #     cpu: 25m
        #   requests:
        #     memory: 150Mi
        #     cpu: 25m
        # livenessProbe:
        #   httpGet:
        #     path: "/health/status"
        #     port: 13133
        #   initialDelaySeconds: 5
        #   failureThreshold: 5
        # readinessProbe:
        #   httpGet:
        #     path: "/health/status"
        #     port: 13133
        #   initialDelaySeconds: 5
        #   failureThreshold: 1
        volumeMounts:
          - name: varlogpods
            mountPath: /var/log/pods
            readOnly: true
          - name: varlogcontainers
            mountPath: /var/log/containers
            readOnly: true
      volumes:
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector
  namespace: monitoring
spec:
  selector:
    app: opentelemetry-collector
  ports:
  - protocol: TCP
    name: "grpc-receiver"
    port: 4317
    targetPort: 4317
  - protocol: TCP
    name: "zpages-extension"
    port: 55679
    targetPort: 55679
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-collector
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetry-collector-k8sattributes
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentelemetry-collector
subjects:
- kind: ServiceAccount
  name: opentelemetry-collector
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: opentelemetry-collector-k8sattributes
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetry-collector-kubeletstats
rules:
  - apiGroups: ['']
    resources: 
      - 'nodes/stats'
      - 'nodes/proxy'
    verbs: ['get', 'watch', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentelemetry-collector-k8s-kubelet
subjects:
  - kind: ServiceAccount
    name: opentelemetry-collector
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: opentelemetry-collector-kubeletstats
  apiGroup: rbac.authorization.k8s.io
