apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector
  namespace: monitoring
  labels:
    app: opentelemetry-collector
data:
  PROMETHEUS__HOST: "http://prometheus:9090"
  NODE_EXPORTER__HOST: "node-exporter:9100"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: opentelemetry-collector
  namespace: monitoring
  labels:
    app: opentelemetry-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry-collector
  template:
    metadata:
      labels:
        app: opentelemetry-collector
    spec:
      serviceAccountName: opentelemetry-collector
      containers:
      - name: opentelemetry-collector
        image: docker.santelos.com/opentelemetry-collector
        ports:
        - containerPort: 4317
        - containerPort: 55679
        envFrom:
          - configMapRef:
              name: opentelemetry-collector
        livenessProbe:
          httpGet:
            path: "/health/status"
            port: 13133
          initialDelaySeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: "/health/status"
            port: 13133
          initialDelaySeconds: 5
          failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector
  namespace: monitoring
spec:
  selector:
    app: opentelemetry-collector
  ports:
  - protocol: TCP
    name: "grpc-receiver"
    port: 4317
    targetPort: 4317
  - protocol: TCP
    name: "zpages-extension"
    port: 55679
    targetPort: 55679
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-collector
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetry-collector
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentelemetry-collector
subjects:
- kind: ServiceAccount
  name: opentelemetry-collector
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: opentelemetry-collector
  apiGroup: rbac.authorization.k8s.io