apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  namespace: monitoring
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/md0/prometheus
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - pstroganov
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  serviceName: prometheus
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: prometheus
          image: docker.santelos.com/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /prometheus
              name: prometheus-volume-claim
              subPath: postgres-data
          resources:
            limits:
              memory: 150Mi
              cpu: 25m
            requests:
              memory: 150Mi
              cpu: 25m
          livenessProbe:
            httpGet:
              path: "/"
              port: 9090
            initialDelaySeconds: 5
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/"
              port: 9090
            initialDelaySeconds: 5
            timeoutSeconds: 10
            failureThreshold: 1
  volumeClaimTemplates:
    - metadata:
        name: prometheus-volume-claim
        labels:
          app: prometheus
      spec:
        storageClassName: local-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
