apiVersion: v1
kind: Secret
metadata:
  name: hydra
  labels:
    app: hydra
type: Opaque
data:
  SECRETS_SYSTEM: eW91UmVhbGx5TmVlZFRvQ2hhbmdlVGhpcw==
  DSN: cG9zdGdyZXM6Ly9oeWRyYTpwYXNzd29yZEBoeWRyYS1kYjo1NDMyL2h5ZHJh
