apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: main
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.santelos.com/frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 6Mi
            cpu: 50m
          requests:
            memory: 6Mi
            cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: main
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: main
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "santelos.com"
    secretName: santelos-cert
  rules:
  - host: santelos.com
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
