services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  service:
    build: .
    ports:
      - 80:80
    environment:
      DATABASE__DATABASE_NAME: postgres
      DATABASE__HOST: database
      DATABASE__PASSWORD: postgres
      DATABASE__USERNAME: postgres