apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - yace-exporter.yaml
configMapGenerator:
  - name: yace-exporter-config
    namespace: monitoring
    options:
      disableNameSuffixHash: true
    files:
      - config.yaml=yace-exporter-config.yaml
