apiVersion: v1
kind: Secret
metadata:
  name: yace-exporter
  namespace: monitoring
  labels:
    app: yace-exporter
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "QUtJQVNMUVNNTEhSSFJCNk9HRU0="
  AWS_SECRET_ACCESS_KEY: "RUpwMGs4bWhXcmMvSWJ3VE5TSDVCUmNXa1JMd09na2dtMGY2ZkRJTg=="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yace-exporter
  namespace: monitoring
  labels:
    app: yace-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yace-exporter
  template:
    metadata:
      labels:
        app: yace-exporter
    spec:
      containers:
        - name: yace-exporter
          image: ghcr.io/nerdswords/yet-another-cloudwatch-exporter:v0.56.0
          imagePullPolicy: IfNotPresent
          args:
            - "--config.file=/etc/yace/config.yaml"
          volumeMounts:
            - name: yace-exporter-config
              mountPath: /etc/yace
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: yace-exporter
          resources:
            requests:
              memory: 200Mi
              cpu: 150m
            limits:
              memory: 200Mi
              cpu: 200m
      volumes:
        - name: yace-exporter-config
          configMap:
            name: yace-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: yace-exporter
  namespace: monitoring
spec:
  selector:
    app: yace-exporter
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
