receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 5s
          static_configs:
            - targets: ['0.0.0.0:8888']
        # - job_name: node-exporter
        #   scrape_interval: 5s
        #   static_configs:
        #     - targets: ['${env:NODE_EXPORTER__HOST}']
        # - job_name: prometheus-k8s
        #   scrape_interval: 5s
        #   static_configs:
        #     - targets: ['${env:PROMETHEUS_K8S__HOST}']

processors:
  batch:
  k8sattributes:
    auth_type: "serviceAccount"
    passthrough: false


exporters:
  logging:
    loglevel: debug
  prometheusremotewrite:
    endpoint: ${env:PROMETHEUS__HOST}/api/v1/write
    tls:
      insecure: true
    resource_to_telemetry_conversion:
      enabled: true

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
    path: "/health/status"

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [k8sattributes, batch]
      exporters: [logging]
    metrics:
      receivers: [otlp, prometheus]
      processors: [k8sattributes, batch]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [k8sattributes, batch]
      exporters: [logging]
