receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 5s
          static_configs:
            - targets: ['0.0.0.0:8888']
        - job_name: node-exporter
          scrape_interval: 5s
          static_configs:
            - targets: ['${env:NODE_EXPORTER__HOST}']

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  prometheusremotewrite:
    endpoint: ${env:PROMETHEUS__HOST}/api/v1/write
    tls:
      insecure: true
    resource_to_telemetry_conversion:
      enabled: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
