receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317

processors:
  batch:

exporters:
  otlp:
    endpoint: ${env:OPENTELEMETRY_HOST}
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
    path: "/health/status"

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
