apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: home
    app.kubernetes.io/name: home
  name: home
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: internet-checker
  namespace: home
  labels:
    app: internet-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internet-checker
  template:
    metadata:
      labels:
        app: internet-checker
    spec:
      containers:
      - name: internet-checker
        image: docker.santelos.com/internet-checker
        ports:
          - containerPort: 9115
---
apiVersion: v1
kind: Service
metadata:
  name: internet-checker
  namespace: home
spec:
  selector:
    app: internet-checker
  ports:
  - protocol: TCP
    port: 9115
    targetPort: 9115