apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - loki.yaml
configMapGenerator:
  - name: loki-config
    namespace: monitoring
    options:
      disableNameSuffixHash: true
    files:
      - loki.ini=loki-config.ini
