apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'node-exporter-job'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          regex: 'node-exporter'
          action: keep
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: k8s_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: k8s_service_name
      - job_name: 'web-services-job-unauth'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          regex: 'true'
          action: keep
        - source_labels: [__meta_kubernetes_service_annotation_metrics_auth_type]
          regex: 'none'
          action: keep
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: k8s_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: k8s_service_name
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
      - job_name: 'web-services-job-oauth2'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          regex: 'true'
          action: keep
        - source_labels: [__meta_kubernetes_service_annotation_metrics_auth_type]
          regex: 'oauth2'
          action: keep    
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: k8s_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: k8s_service_name
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        oauth2:
          client_id: 8577ae59-9617-433b-b58e-fba04dcb77da
          client_secret_file: /k8s-secret/oauth2-client-secret
          scopes:
            - internal:metrics
          token_url: http://id.santelos.com/o/oauth2/token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--storage.tsdb.retention.time=12h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--log.level=debug"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: "/etc/prometheus/"
            - name: prometheus-secret
              mountPath: "/k8s-secret"
              readOnly: true
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        - name: prometheus-secret
          secret:
            secretName: prometheus-secret
            items:
              - key: OAUTH2_CLIENT_SECRET
                path: oauth2-client-secret
