name: 'Docker-Compose | Infrastructure'

on:
  push:
    branches:
      - main
    paths:
      - infrastructure/docker-compose/infrastructure/**
      - .github/workflows/infrastructure_docker-compose_infrastructure.yml
  pull_request:
    paths:
      - infrastructure/docker-compose/infrastructure/**
      - .github/workflows/infrastructure_docker-compose_infrastructure.yml

permissions:
  id-token: write

defaults:
  run:
    working-directory: infrastructure/docker-compose/infrastructure/

env:
  AWS_ROLE: ${{ secrets.AWS_ROLE }}
  AWS_REGION: eu-central-1
  TARGET_PATH: infrastructure

jobs:
  ec2_sync:
    name: 'EC2 Sync'
    runs-on: ubuntu-latest
    environment: Infrastructure | Docker-Compose | Infrastructure

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install ec2instanceconnectcli

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.AWS_ROLE }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Configure SSH
      run: |
        mkdir ~/.ssh && touch ~/.ssh/known_hosts
        ssh-keyscan -H ${{ secrets.HOST_IP }} >> ~/.ssh/known_hosts

    - name: Sync
      run: rsync -a -e mssh . ${{ secrets.HOST_ID }}:${{ env.TARGET_PATH }}

    - name: Run SSH
      run: |
        mssh ${{ secrets.HOST_ID }} << EOF
        cd ${{ env.TARGET_PATH }}
        docker-compose up -d
        