name: 'Docker-Compose | Infrastructure'

on:
  push:
    branches:
      - main
    paths:
      - infrastructure/docker-compose/infrastructure/**
      - .github/workflows/infrastructure_docker-compose_infrastructure.yml
  pull_request:
    paths:
      - infrastructure/docker-compose/infrastructure/**
      - .github/workflows/infrastructure_docker-compose_infrastructure.yml

permissions:
  id-token: write

defaults:
  run:
    working-directory: infrastructure/docker-compose/infrastructure/

env:
  AWS_ROLE: arn:aws:iam::162173573602:role/common/ec2-connect
  AWS_REGION: eu-central-1
  TARGET_PATH: infrastructure

jobs:
  aws_push:
    name: 'AWS Push'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install mssh
      run: pip install ec2instanceconnectcli

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.AWS_ROLE }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Configure SSH
      run: |
        ssh-keygen -t rsa -b 4096 -N "" -f ~/.ssh/id_rsa   

    # - name: Sync Docker-Compose
    #   run: rsync -a -e mssh . ${{ secrets.INSTANCE_ID }}:~/${{ env.TARGET_PATH }}

    - name: Apply Docker-Compose
      run: mssh i-01fc62f4e0ddefc27
        